# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e18b862342c5e54c13e3a48b3da40677ac6493034ba9aa3fbb12ae8c3ff47aaa7b088216933d84379aefb33e6841d6a2ebc4fc94ec7682963c481c30a8ba722b

test:
  secret_key_base: cb10ff1ec84608b3c7b87f07521febf1ac1e46e4904fdc24b6606aa4d8af15675318319bed90a8e88e7db1be20c830961f0dde815b0cc40439978337b856461a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
